apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: final
spec:
  selector:
    app: employee
  type: NodePort
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
      nodePort: 30000
