apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: final
spec:
  selector:
    app: employee
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: app-deployment
      port: 81
      targetPort: 81
