apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: final
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: db-deployment
        image: 009147451403.dkr.ecr.us-east-1.amazonaws.com/prod-db:test
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
        ports:
          - containerPort: 3306
        volumeMounts:
          - mountPath: /data
            name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always